config/routes.rb
Rails.application.routes.draw do
  get 'librarian_actions/index'

  get 'librarian_actions/new'

  devise_for :librarians
  get 'home/index'

  root 'home#index'

  resources :reservations
  resources :clients
  resources :books
  resources :authors

  get '/novo_bibliotecario', to: 'librarian_actions#index', as: 'librarians'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_librarian!

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>


<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>


<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>