config/routes.rb
Rails.application.routes.draw do
  get 'librarian_actions/index'

  get 'librarian_actions/new'

  devise_for :librarians
  get 'home/index'

  root 'home#index'

  resources :reservations
  resources :clients
  resources :books
  resources :authors

  get '/novo_bibliotecario', to: 'librarian_actions#index', as: 'librarians'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :book
  belongs_to :client
  belongs_to :librarian
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_librarian!
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    book_options_for_select
    client_options_for_select
    librarian_options_for_select
  end

  # GET /reservations/1/edit
  def edit
    ok_options_for_select
    client_options_for_select
    librarian_options_for_select
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def book_options_for_select
      @book_options_for_select=Book.all
    end

    def client_options_for_select
      @client_options_for_select=Client.all
    end

    def librarian_options_for_select
      @librarian_options_for_select=Librarian.all
    end

    
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:book_id, :client_id, :librarian_id, :status)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= collection_select(:reservation, :book_id, @book_options_for_select, :id, :title) %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= collection_select(:reservation, :client_id, @client_options_for_select, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :librarian_id %>
    <%= collection_select(:reservation, :librarian_id, @librarian_options_for_select, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>   $('select').selectize({     sortField: 'string' }); </script>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Client</th>
      <th>Librarian</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.book.title %></td>
        <td><%= reservation.client.name %></td>
        <td><%= reservation.librarian.name %></td>
        <td><%= reservation.status %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>


<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @reservation.book.title %>
</p>

<p>
  <strong>Client:</strong>
  <%= @reservation.client.name %>
</p>

<p>
  <strong>Librarian:</strong>
  <%= @reservation.librarian.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reservation.status %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

<h1>Menu</h1>
<li><%= link_to "Livros", books_path %></li>
    <li><%= link_to "Autores", authors_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    <li><%= link_to "Bibliotecários", librarians_path %></li>
    <li><%= link_to "Reservas", reservations_path %></li>
    <ul></ul>
    <li><%= link_to "Voltar para Menu", home_index_path %></li>